# Default pipeline locations for Planetarble
data_dir: data
temp_dir: tmp
output_dir: output
processing:
  bmng_resolution: "500m"
  gebco_year: 2024
  natural_earth_scale: "10m"
  color_enhancement: 1.05
  hillshade_opacity: 0.15
  max_zoom: 10
  tile_format: "JPEG"
  tile_quality: 95
  tile_source: "modis"
  modis_enabled: true
  modis_doy: "2025233"
  modis_tiles:
    - h27v04
    - h28v04
    - h28v05
    - h29v05
    - h29v06
    - h30v05
  modis_tile_source: "modis"
  modis_scale_min: 0
  modis_scale_max: 2500
  modis_gamma: 0.7
  viirs_enabled: false
  viirs_date: "2025233"
  viirs_tiles:
    - h27v04
    - h28v04
    - h28v05
    - h29v05
    - h29v06
    - h30v05
  viirs_product: "VNP09GA.002"
  viirs_scale_min: 0
  viirs_scale_max: 9000
  viirs_gamma: 0.8
copernicus:
  enabled: true
  bbox:
    - 123.0
    - 24.0
    - 147.0
    - 46.0
  min_zoom: 8
  max_zoom: 12
  tile_size: 256
  max_tiles_per_layer: null
  timeout_seconds: 30
  layers:
    - name: TRUE_COLOR
      format: image/jpeg
      output: true_color
    - name: VEGETATION_INDEX
      format: image/png
      output: vegetation_index
