# Default pipeline locations for Planetarble
data_dir: data
temp_dir: tmp
output_dir: output
processing:
  bmng_resolution: "500m"
  gebco_year: 2024
  natural_earth_scale: "10m"
  color_enhancement: 1.05
  hillshade_opacity: 0.15
  max_zoom: 10
  tile_format: "JPEG"
  tile_quality: 80
