# Default pipeline locations for Planetarble
data_dir: data
temp_dir: tmp
output_dir: output
processing:
  bmng_resolution: "500m"
  gebco_year: 2024
  natural_earth_scale: "10m"
  color_enhancement: 1.05
  hillshade_opacity: 0.15
  max_zoom: 12
  resampling: "cubic"
  tile_format: "JPEG"
  tile_quality: 75
  tile_source: "bmng"
modis:
  enabled: false
  doy: "2025233"
  tiles:
    - h27v04
    - h28v04
    - h28v05
    - h29v05
    - h29v06
    - h30v05
  scale_min: 0
  scale_max: 2500
  gamma: 0.7
viirs:
  enabled: false
  date: "2025233"
  tiles:
    - h27v04
    - h28v04
    - h28v05
    - h29v05
    - h29v06
    - h30v05
  product: "VNP09GA.002"
  scale_min: 0
  scale_max: 9000
  gamma: 0.8
copernicus:
  enabled: false
  bbox:
    - 123.0
    - 24.0
    - 147.0
    - 46.0
  min_zoom: 8
  max_zoom: 14
  tile_size: 256
  max_tiles_per_layer: null
  timeout_seconds: 30
  request_interval_seconds: 0.5
  max_retries: 3
  backoff_factor: 2.0
  layers:
    - name: TRUE_COLOR
      format: image/jpeg
      output: true_color
gsi_orthophotos:
  enabled: true
  lat: 35.681236
  lon: 139.767125
  width_m: 3000
  height_m: 3000
  zoom: 18
  tile_template: "https://cyberjapandata.gsi.go.jp/xyz/seamlessphoto/{z}/{x}/{y}.jpg"
  output_basename: "gsi_orthophotos"
  timeout_seconds: 60
