"""Miniplanet subdivisions for incremental, balanced HLS planning.

planetarble can split a global HLS build into a fixed set of size-balanced,
mutually-exclusive, globally-exhaustive regions ("miniplanets"), each identified
by a stable two-digit id. The scheme follows the approach of the public
``@geolonia/osm-miniplanets`` / ``un-vector-tile-toolkit/duodecim`` projects --
axis-aligned rectangles expressed in z=BASE_ZOOM tile coordinates, with a tile's
miniplanet resolved by locating its z=BASE_ZOOM ancestor -- but the boundaries
here are *recomputed* to balance planetarble's own workload (the number of land
ZL10 composite tiles per region) rather than OSM ``planet.osm.pbf`` byte size.

``SUBDIVISIONS`` is generated by ``tools/gen_miniplanets.py`` using the
``compute_subdivisions`` recursive coordinate bisection below. Regenerate the
table (e.g. with a finer land mask) and paste the result here.

This module is intentionally dependency-free (no GDAL, no network) so it can be
imported and tested in isolation.
"""

from __future__ import annotations

import math
from typing import List, Optional, Tuple

BASE_ZOOM = 6

BBox = Tuple[int, int, int, int]  # z=BASE_ZOOM tile coords, inclusive: (minx, miny, maxx, maxy)

# Generated by tools/gen_miniplanets.py (regions=18), balanced by MEASURED land
# ZL10 tile counts aggregated from the generated per-shard plans (407,072 tiles
# with the ne_10m_land mask; balance ratio max/min = 1.26). Mutually exclusive
# and exhaustive over the 2**BASE_ZOOM x 2**BASE_ZOOM grid. Do not hand-edit;
# regenerate with tools/gen_miniplanets.py --plans instead.
SUBDIVISIONS: Tuple[BBox, ...] = (
    (0, 0, 18, 17),    # tiles=23909 (5.9%)
    (0, 18, 18, 27),   # tiles=22322 (5.5%)
    (19, 0, 35, 13),   # tiles=21485 (5.3%)
    (19, 14, 35, 27),  # tiles=21530 (5.3%)
    (0, 28, 17, 57),   # tiles=19772 (4.9%)
    (0, 58, 17, 63),   # tiles=23311 (5.7%)
    (18, 28, 35, 40),  # tiles=22169 (5.4%)
    (18, 41, 35, 58),  # tiles=21538 (5.3%)
    (18, 59, 35, 63),  # tiles=22588 (5.5%)
    (36, 0, 48, 19),   # tiles=23464 (5.8%)
    (49, 0, 63, 19),   # tiles=21006 (5.2%)
    (36, 20, 45, 31),  # tiles=24533 (6.0%)
    (46, 20, 63, 31),  # tiles=23539 (5.8%)
    (36, 32, 49, 53),  # tiles=23868 (5.9%)
    (50, 32, 63, 53),  # tiles=24981 (6.1%)
    (36, 54, 44, 63),  # tiles=23394 (5.7%)
    (45, 54, 52, 63),  # tiles=20736 (5.1%)
    (53, 54, 63, 63),  # tiles=22927 (5.6%)
)


def miniplanet_ids() -> List[str]:
    """Return all miniplanet ids as zero-padded two-digit strings."""
    return [_format_id(i) for i in range(len(SUBDIVISIONS))]


def subdivision_z6_bbox(mp_id: str) -> BBox:
    """Return the z=BASE_ZOOM tile bbox (inclusive) for a miniplanet id."""
    return SUBDIVISIONS[_id_to_index(mp_id)]


def miniplanet_geo_bbox(mp_id: str) -> Tuple[float, float, float, float]:
    """Return the geographic bbox (lon_min, lat_min, lon_max, lat_max) for a miniplanet."""
    minx, miny, maxx, maxy = subdivision_z6_bbox(mp_id)
    # west/north come from the top-left tile, east/south from the bottom-right tile.
    west, _, _, north = _tile_bounds(BASE_ZOOM, minx, miny)
    _, south, east, _ = _tile_bounds(BASE_ZOOM, maxx, maxy)
    return (west, south, east, north)


def tile_to_miniplanet_id(z: int, x: int, y: int) -> Optional[str]:
    """Return the miniplanet id owning tile (z, x, y), or None for z < BASE_ZOOM.

    Tiles at z >= BASE_ZOOM map to exactly one miniplanet via their z=BASE_ZOOM
    ancestor, because SUBDIVISIONS is a partition of the z=BASE_ZOOM grid.
    """
    if z < BASE_ZOOM:
        return None
    shift = z - BASE_ZOOM
    ax = x >> shift
    ay = y >> shift
    for index, (minx, miny, maxx, maxy) in enumerate(SUBDIVISIONS):
        if minx <= ax <= maxx and miny <= ay <= maxy:
            return _format_id(index)
    return None  # pragma: no cover -- unreachable when SUBDIVISIONS is exhaustive


def compute_subdivisions(
    weight: List[List[float]],
    n: int,
    extent: Optional[BBox] = None,
) -> List[BBox]:
    """Partition a grid extent into ``n`` rectangles of roughly equal weight.

    Uses recursive coordinate bisection: at each step the box is split along its
    longer axis into ``n//2`` / ``n-n//2`` leaves, choosing the cut so the lighter
    side carries its proportional share of the weight while keeping at least one
    cell (one leaf) per leaf-count on each side. The result tiles ``extent``
    exactly with no overlaps or gaps.

    ``weight`` is indexed ``weight[x][y]``.
    """
    if n < 1:
        raise ValueError("n must be >= 1")
    if extent is None:
        size_x = len(weight)
        size_y = len(weight[0]) if weight else 0
        extent = (0, 0, size_x - 1, size_y - 1)
    return _rcb(extent, n, weight)


def _rcb(box: BBox, n: int, weight: List[List[float]]) -> List[BBox]:
    x0, y0, x1, y1 = box
    if n == 1:
        return [box]
    width = x1 - x0 + 1
    height = y1 - y0 + 1
    if width < n and height < n and width * height < n:
        raise ValueError(f"box {box} too small to split into {n} regions")

    nl = n // 2
    nr = n - nl
    total = _box_weight(box, weight)
    target = total * nl / n

    split_x = width >= height
    # Ensure each side keeps enough cells for its leaf count.
    if split_x and width >= n:
        cut = _best_cut(
            lambda c: _box_weight((x0, y0, c, y1), weight),
            lo=x0 + nl - 1,
            hi=x1 - nr,
            target=target,
        )
        left = (x0, y0, cut, y1)
        right = (cut + 1, y0, x1, y1)
    elif height >= n:
        cut = _best_cut(
            lambda c: _box_weight((x0, y0, x1, c), weight),
            lo=y0 + nl - 1,
            hi=y1 - nr,
            target=target,
        )
        left = (x0, y0, x1, cut)
        right = (x0, cut + 1, x1, y1)
    else:
        # Longer axis too short for the leaf count; fall back to the other axis.
        cut = _best_cut(
            lambda c: _box_weight((x0, y0, c, y1), weight),
            lo=x0 + nl - 1,
            hi=x1 - nr,
            target=target,
        )
        left = (x0, y0, cut, y1)
        right = (cut + 1, y0, x1, y1)

    return _rcb(left, nl, weight) + _rcb(right, nr, weight)


def _best_cut(cum_weight_at, lo: int, hi: int, target: float) -> int:
    """Return the cut index in [lo, hi] whose left-weight is closest to target.

    Deterministic: ties resolve to the lowest index.
    """
    best_index = lo
    best_diff: Optional[float] = None
    for c in range(lo, hi + 1):
        diff = abs(cum_weight_at(c) - target)
        if best_diff is None or diff < best_diff:
            best_diff = diff
            best_index = c
    return best_index


def _box_weight(box: BBox, weight: List[List[float]]) -> float:
    x0, y0, x1, y1 = box
    total = 0.0
    for x in range(x0, x1 + 1):
        col = weight[x]
        for y in range(y0, y1 + 1):
            total += col[y]
    return total


def _format_id(index: int) -> str:
    return str(index).zfill(2)


def _id_to_index(mp_id: str) -> int:
    try:
        index = int(mp_id)
    except (TypeError, ValueError) as exc:
        raise KeyError(f"invalid miniplanet id: {mp_id!r}") from exc
    if not 0 <= index < len(SUBDIVISIONS):
        raise KeyError(f"unknown miniplanet id: {mp_id!r}")
    return index


def _tile_bounds(z: int, x: int, y: int) -> Tuple[float, float, float, float]:
    n = 1 << z
    lon_min = x / n * 360.0 - 180.0
    lon_max = (x + 1) / n * 360.0 - 180.0
    lat_min = _tile_latitude(y + 1, n)
    lat_max = _tile_latitude(y, n)
    return (lon_min, lat_min, lon_max, lat_max)


def _tile_latitude(y: int, n: int) -> float:
    merc_y = math.pi * (1 - 2 * y / n)
    lat_rad = math.atan(math.sinh(merc_y))
    return math.degrees(lat_rad)
